// External libraries
global using System.Reflection;
global using Carter;
global using FluentValidation;
global using Microsoft.Extensions.Options;
global using Microsoft.OpenApi.Any;
global using Microsoft.OpenApi.Models;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Swashbuckle.AspNetCore.SwaggerUI;
global using Asp.Versioning.ApiExplorer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;

// Project namespaces
global using netflix_clone_auth.Api.DependencyInjection.Options;
global using netflix_clone_auth.Api.DependencyInjection.Extensions;
global using netflix_clone_auth.Api.Endpoints.Requests;
global using netflix_clone_auth.Api.Persistence;
global using netflix_clone_auth.Api.Settings;
global using netflix_clone_auth.Api.Persistence.Entitiy;
global using netflix_clone_shared;
global using netflix_clone_shared.Entities;
global using netflix_clone_shared.Mediator;
global using netflix_clone_shared.Middlewares;
global using netflix_clone_shared.Idempotence;
global using netflix_clone_shared.CQRS;
global using netflix_clone_shared.Results;
